### ISSUE TITLE
iGPU PM

### ISSUE THREAD

**Issue by Nomad347** [syscl/XPS9350-macOS#31] opened 2017-01-24 21:12 UTC
First I just want to take a minute and THANK YOU for everything. More than I could ever want for my XPS. I use it as a daily driver now. One issue that I have not managed to get working is GPU PM. I get a panic if I boot with the generate SSDT pr table. No matter what I do. If I boot without it, then there's no PM for GPu.
I tried modifying  the deploy sh script in the define variable section and select the non Iris version but still a no go. ioreg+clover folder attached. Keep up the good work.

EDIT: Amazing. it worked. Igpu present in IOREgEXPL
![untitled](https://cloud.githubusercontent.com/assets/24359843/22302784/472d4368-e328-11e6-8f63-34d76b85c4d4.jpeg)

**Comment by syscl** [comment] 2017-01-24 21:18
Hi @Nomad347 

I am switching to SSDT-pr(Generate P/CStates) mode to get complete power management. Here's what you need to do if you want full power management
```sh
git clone https://github.com/Piker-Alpha/freqVectorsEdit.sh
cd ./freqVectorsEdit.sh
chmod +x ./*.sh
```

Now you can run freqv script at any time if you want
```sh
./freqVectorsEdit.sh
```

Choose MacBookPro12,1 then reboot to enjoy the full power management.

Note: You need to turn off HWP if you use SSDT-pr table. Don't use them both. I now want to figure out why there's no full power management when HWP is enabled. And I have no clue if new MacBookPro use HWP or not. 

syscl

**Comment by syscl** [comment] 2017-01-26 02:03
@Nomad347 I do not see your ioreg and clover folder..

What specs you have? Do you use SSDT-pr now? Why your CPU freq is very low and have a pretty good power consume? 

I tried some method to lower down the power consume, here's the screenshot
![snip20170125_1](https://cloud.githubusercontent.com/assets/11594858/22317455/5b77e1b4-e339-11e6-91d2-21a32a7340e3.png)


syscl

**Comment by syscl** [comment] 2017-01-26 02:24
@Nomad347 Now I can lower the freqv down even, but I still need more test to see if this configuration is stable

![snip20170125_12](https://cloud.githubusercontent.com/assets/11594858/22317898/43054740-e33c-11e6-829a-1a776652e244.png)


syscl

**Comment by Nomad347** [comment] 2017-01-26 17:10
Sorry I replaced them with the screenshot. My model is the Full HD non Iris i6200 model. I tried in several configs but your ssdt pr aml does not work for me. I get instant cpu panics each time. Even after modifying the deploy.sh script to target non iris systems. (is that implemented yet though?). Amazing work btw. Your suggestion with piker's frequency vectors was the one that finally injected ogpu PM. Used MacBook Air 6,2. His script also has MacBook Pro 13,1 and 13,3. Would that be more appropriate since it's skylake?

Keep it up man.
[Archive.zip](https://github.com/syscl/XPS9350-macOS/files/732965/Archive.zip)

**Comment by syscl** [comment] 2017-01-28 05:06
Hi @Nomad347 , how about using your SSDT-pr with my script?

syscl

**Comment by Nomad347** [comment] 2017-01-28 09:09
No go. Panic each time. As soon as i put a proc ssdt either the one generated with your script or one that i generate with pikes script i get an instant panic. Havent tried one after using the frequency vectors scipt. Do I need to undo that? And how?

**Comment by syscl** [comment] 2017-01-28 16:39
@Nomad347 ,

What I curious about is that: panic only happen when you use SSDT-pr + deploy.sh + freqv.sh?

Do you disable HWP in config.plist? I want to pinpoint your issue.

syscl

**Comment by Nomad347** [comment] 2017-01-29 10:19
[Archive.zip](https://github.com/syscl/XPS9350-macOS/files/737432/Archive.zip)

 SSDT-pr + deploy.sh + freqv.sh works. No more panics. iGPU loads. Seems to work as well as the Generate P and C states I used before with Clover.

Thanks for your help. Mark solved. Let me know if you need any other files/logs.

**Comment by squash-** [comment] 2017-01-29 16:22
@Nomad347

What did you change or do to get the SSDT-pr.aml working? I get kernel panics with it too or if I generate c and p stars with clover.

**Comment by Nomad347** [comment] 2017-01-29 18:17
see post 2 above

**Comment by syscl** [comment] 2017-01-29 19:07
@Nomad347 does your AppleALC have external mic support? For example, when iPhone's headphone plug in, sound can be recorded from headphone's mic.

syscl

**Comment by syscl** [comment] 2017-01-29 19:21
@Nomad347 I tried, but no sound
![snip20170129_4](https://cloud.githubusercontent.com/assets/11594858/22407114/b7a14572-e625-11e6-9b7c-154bec45a5d4.png)

syscl

**Comment by Nomad347** [comment] 2017-01-29 20:06
using kext posted here. https://www.tonymacx86.com/threads/guide-dell-xps-13-9350-macos-10-12-1.204730/page-61#post-1417411
Post 606. credits to nos1609?

**Comment by syscl** [comment] 2017-02-09 21:57
@Nomad347 Please try full power management with HWP enable.
![snip20170209_5](https://cloud.githubusercontent.com/assets/11594858/22804836/7d6cd18c-eee0-11e6-8548-95d160aca929.png)

syscl

**Comment by squash-** [comment] 2017-02-09 23:13
is FakeSMBIOS kext still needed? If you change to MacBookPro13,2 without changing FakeSMBIOS properties to MacBookPro as well some things still identify as MacBook9,1

**Comment by syscl** [comment] 2017-02-09 23:25
Thank you, I will remove it...now!

syscl

**Comment by syscl** [comment] 2017-02-09 23:27
@squash- I tuned freqvectors as well, otherwise, the frequencies won't go down. I will try to let deploy tune frequency vectors as well.

Here's the screenshot
![snip20170209_6](https://cloud.githubusercontent.com/assets/11594858/22807523/17a1a014-eeed-11e6-87ce-b00a493304d5.png)

syscl

**Comment by Nomad347** [comment] 2017-02-10 19:50
Wow man. Just tried it out. Works very well. Hope I won't get any hdd corruption with HWP. Had one corruption of EFI partition before. Not the easiest error to recover from.

But again. WOW.
Can you explain what the values of freq vectors represent? Are those the p states that correspond to a certain proc freq? And how do you get the vale? I assume it's hex...

BTW> you can close the thread. It's solved from my point of view.

Thanks again man. Slowly but surely you are tuning into a legend of the hackintosh scene. 

Congrats on being featured on 9to5mac btw.

**Comment by squash-** [comment] 2017-02-10 20:16
@Nomad347 I assuble that the 2nd position in that set of hex bytes is the idle clock speed multiplier? because by default for the MacBookPro13,2 plist it is d which is 13 in hex so 13x100MHz would be 1.3GHz. so he changed it to 5 so that it ramps down to a 500MHz idle. 5x100MHz = 500MHz. @syscl you're more than welcome to correct me if I am wrong though.

**Comment by ZombieTheBest** [comment] 2017-02-11 18:18
@syscl I will follow this thread for updates regarding Power Management! :) 
Right now with my i7-6600U, HWP and MacBook Pro plist frequency won't go less than 1.3Ghz, with about 2/3W of power consume during normal usage. I will stay updated here :D 
Good Job!!! :)

**Comment by syscl** [comment] 2017-02-12 16:39
This isn't good, what graphics model shown in your system?

You can see this in ```System Report```->```Graphics```


syscl

**Comment by ZombieTheBest** [comment] 2017-02-12 17:09
Intel HD 520
<img width="748" alt="schermata 2017-02-12 alle 18 09 00" src="https://cloud.githubusercontent.com/assets/22716366/22864258/5eb6d57e-f14e-11e6-90d9-3f57dda6df91.png">

**Comment by syscl** [comment] 2017-02-12 17:34
@ZombieTheBest Great, seems geekbench's bug.

syscl

**Comment by ZombieTheBest** [comment] 2017-02-12 18:05
@syscl Nice! I've found a minor bug with audio being distorted after resume: it can be fixed easily by going into `Settings->Audio` and it fixes it by itself. On my config I have not experienced any Partition Corruption caused by sleep yet :)

**Comment by syscl** [comment] 2017-02-12 18:08
@ZombieTheBest Which model you owned? I mean: AHCI SSD or NVME? Because I and many others who have NVME driver have experienced data corruption while sleep(occur reasons remains unknown) Thus I recommend you to backup your system if you use sleep function frequently. 

If you can confirm AHCI SSD has no data corruption with sleep, I will be very happy to narrow the question's range. Thank you!

syscl

**Comment by ZombieTheBest** [comment] 2017-02-12 18:18
@syscl Toshiba M2 NVMe Drive. Of course I have no important datas in this laptop, as I use Google Drive for docs, and everything is backed up. I frequently use sleep and hibernation (I think: when the laptop is sleeping for a long time and I open it up again I have to press the power button to power it on). In this week I had no problem at all, I will keep you updated if something happens! 👍 
<img width="748" alt="schermata 2017-02-12 alle 19 16 35" src="https://cloud.githubusercontent.com/assets/22716366/22864784/ceea2c7a-f157-11e6-98b4-74550c514c34.png">

**Comment by nos1609** [comment] 2017-02-14 21:21
@squash- I reached even 400 Mhz under macOS, but it was uncontrolled and the frequency remains blocked all the time the os is running. It was really sloooow as usage experience :)

**Comment by ZombieTheBest** [comment] 2017-02-15 09:16
@syscl I can confirm still no sleep issues nor damaged partition on my NVMe Disk. And I have put my dell at sleep at least 10 to 30 times. I will keep you updated if something happens 👍

**Comment by ZombieTheBest** [comment] 2017-02-21 22:13
Hi @syscl 
I saw you have updated sleep (added hybernation?). I got no sleep issue so far. Today I've reinstalled Clover with RC-script option (I didn't had that) and ran the last Deploy a few minutes ago.
There's just a "Failed" message of a missing kext in kext folders of the project, can't remember the name and forgot to write that down, but seems nothing relevant, maybe take a look into it! 👍  
If necessary I will run it again and post here the output. Thank you and again, good job!

**Comment by syscl** [comment] 2017-02-21 22:14
@ZombieTheBest Please re run deploy.sh again to see if the log still has ```failed```.

syscl

**Comment by ZombieTheBest** [comment] 2017-02-21 22:20
Sure. here's the line: 

```
[FAILED]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/OsxFatBinaryDrv-64.efi.
cp: /Users/mirco/Downloads/XPS9350-macOS-master/CLOVER/drivers64UEFI/OsxFatBinaryDrv-64.efi: No such file or directory
```

**Comment by syscl** [comment] 2017-02-21 23:47
@ZombieTheBest Thank you, please try latest deploy.sh

syscl

**Comment by ZombieTheBest** [comment] 2017-02-22 07:43
Hi @syscl !
Tried your latest patch, no more failed error. Just one more thing: there's a "md5" error, don't know if that's relevant again 👍 

And another question: how is supposed deep sleep to work? I mean, laptop should go in hibernation after a while after sleep? Thank you!
```
[  OK  ]  Create /tmp/RecoveryHD.
[  OK  ]  Create /Users/mirco/Downloads/XPS9350-macOS-master/Backups/2017-02-22-h08_39_47.
md5: /tmp/BaseSystem_PATCHED.dmg: No such file or directory
[ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
[  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
```

**Comment by nos1609** [comment] 2017-02-22 08:02
@ZombieTheBest sleep behaviour can be tuned by `sudo pmset` [command](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pmset.1.html).

**Comment by ZombieTheBest** [comment] 2017-02-22 08:46
@nos1609 Hi, thank you for your answer. I'm trying to tell him to go to hibernate after a certain amount of time of sleep. I'm following this tutorial: https://computers.tutsplus.com/tutorials/how-to-hibernate-a-mac--cms-23235

But there's a problem, when I type `pmset -g`I see no `standby` or `standbydelay` option. 
According to the tutorial: 
`The setting standby will be visible in pmset -g if the feature is supported on the machine.`

Am I doing anything wrong?

**Comment by nos1609** [comment] 2017-02-22 08:57
@ZombieTheBest check the actual info in `man pmset` since the info at dev.apple is meant for 10.9 and is a bit outdated.

**Comment by ZombieTheBest** [comment] 2017-02-22 09:03
Thank you @nos1609, from man pmset I can read exactly same thing I read in that page (they did copy-paste). And do you know how do I fix clover hibernation? :)
Thank you again!

```
standby causes kernel power management to automatically hibernate a
     machine after it has slept for a specified time period. This saves power
     while asleep. This setting defaults to ON for supported hardware. The
     setting standby will be visible in pmset -g if the feature is supported
     on this machine.

     standbydelay specifies the delay, in seconds, before writing the hiberna-
     tion image to disk and powering off memory for Standby.
```

**Comment by nos1609** [comment] 2017-02-22 09:46
@Nomad347 as far as I remember \private have soft links inside for other directories.
Concerning hibernation - you can force it by setting `hibernatemode 25` in `pmset` but mind [making a volume image in disk utility](https://support.apple.com/en-us/HT1553) prior closing the lid with those settings ;)

**Comment by ZombieTheBest** [comment] 2017-02-22 09:52
@nos1609 I was just testing if hibernation worked by setting it to 25. Clover seems to "search" the sleep image file in the right path, but says that it has "invalid offset" from bdmesg. 
Help me understand why should I perform a volume image backup? I mean, in the changelog `Updated sleep: add deep sleep & deep idle properties as per Pike R. Alpha`, isn't supposed to add support to hibernation/hibernation 3? I have an NVMe disk, still had no issues with sleep (damaged partition etc), and I put my laptop at sleep almost 5 to 10 times a day. Should I keep hibernationmode to 0? Thank you!

**Comment by nos1609** [comment] 2017-02-22 11:37
@ZombieTheBest hibernation is still being tested on skylake as far as I know, and since we had issues on that platform better being ready for everything. I'm not able to test the setup till the next week, so actually you're the beta-tester for @syscl recent commits, since even we are all running macOS on the same laptop model, at least they are 4 types of SSDs being used and 4 types of cpus. Personnally I've seen 5 BIOSupdated, several of which changed macOS bahaviour. That is why there might be different experience through the variety of laptops using the script.

Concerning the hibernation issue, try using the 
> Strict Hibernate
option in Clover config combined to a removed 
> \var\vm\sleepimage
file for more pure test. Don't forget checking your BIOS settings that any of the sleep states are not blocked.

@syscl How can we know which msr is being changed by the Intel XTU? I had better scores in geekbench and slightly different frequencies in powergadget after when I wasn't using you config with cpu-related SSDTs drops. I understand that they are dynamic so not intended to be patched, but I suppose that the settings inside might being used from MSRs. To be more precise I had TB Short duration set to 100s instead of defaults 28, peak TPD set to 28W and maximum TPD set to 25W. These setting combined to slight undervolt gave me more juice without overheat (I've modded the thermal dissipation a bit). Such config allowed the GPU consuming up to 23W under stress and the CPU rising up to 19W under load. Maximum TPD seen was 26W but it didn't last for long time. I remember that FinalCut was a bit more faster previously on my laptop ;)

**Comment by ZombieTheBest** [comment] 2017-02-22 12:21
Thank you @nos1609 for your explanation. I'm making an Image Backup as Office Suite wasn't working anymore after hibernation. Strict Hibernate option doesn't seem to have worked (Clover doesn't write "Hibernated" on the boot drive), and bdmesg shows that it cannot find the sleepimage. 

Here's the full bdmesg output:
[bdmesg_output.txt](https://github.com/syscl/XPS9350-macOS/files/793325/bdmesg_output.txt)

**Comment by syscl** [comment] 2017-02-22 16:47
@ZombieTheBest Thank you, please try the latest deploy to see if there's no more error.

syscl

**Comment by ZombieTheBest** [comment] 2017-02-22 17:01
@syscl Fixed ;)

**Comment by syscl** [comment] 2017-02-22 17:06
@squash- @Nomad347 @ZombieTheBest @nos1609 Please try the latest deploy.sh with HWP enable in config.plist.

Now, deploy.sh will install a tuned X86PlatformPluginInjector for your system. In the tuned X86PlatformInjector, there's a lot of optimization and properties I inject for our XPS 13!

syscl

**Closed** 2017-02-26 09:36 UTC
