### ISSUE TITLE
Explain ACPI Patches

### ISSUE THREAD

**Issue by maxexcloo** [syscl/XPS9350-macOS#1] opened 2016-11-17 00:45 UTC
I know it's a big ask but is there any chance you can explain what each patch is for?
I'm trying to learn as much as I can from your work 😄 

https://github.com/syscl/XPS9350-macOS/blob/master/Deploy.sh#L1405

**Comment by syscl** [comment] 2016-11-17 00:58
@maxexcloo This is actually forked from my previous project https://github.com/syscl/M3800

I will refine it to suit XPS 13 9350 as well. But I have to finish my due first, will soon come.

BTW, there's still a lot of new ACPI patches have to implement since today a friend give me all the information from a real MacBook9,1.

syscl

**Comment by maxexcloo** [comment] 2016-11-17 01:04
Thanks man! I'm not sure if you noticed my post on the XPS 13 9350 Guide but I'd love to work together on this (we have different builds, mine is HD520) 👍 
I'm fairly new to the whole process and would love to have a flawless build going!

**Comment by maxexcloo** [comment] 2016-11-17 01:07
Are there any essential patches I've neglected to include (or for that matter, any patches that shouldn't be there?)

DSDT Patches:
[syn] Rename _DSM methods to XDSM
[igpu] Rename GFX0 to IGPU
[igpu] Brightness fix
[sys] Fix _WAK Arg0 v2
[sys] Fix Mutex with non-zero SyncLevel
[sys] HPET Fix
[sys] IRQ Fix
[sys] OS Check Fix (Windows 8)
[sys] RTC Fix
[sys] Skylake LPC
[sys] SMBUS Fix

SSDT-1:
[gfx0] Cleanup/Fix Errors (SSDT)

SSDT-0, SSDT-1, SSDT-2, SSDT-3, SSDT-4, SSDT-5, SSDT-6, SSDT-14:
[igpu] Rename GFX0 to IGPU

Also, is HaltEnabler something I need to enable? What does it do (looked online but couldn't find a simple explanation...

**Comment by syscl** [comment] 2016-11-17 01:09
@maxexcloo HaltEanbler is for those who suffer from reboot panic or shutdown panic users.

In this case, this argument prevent reboot panic.

syscl

**Comment by maxexcloo** [comment] 2016-11-17 01:26
Ah interesting, I haven't had that issue on my XPS!
How about the patches, any feedback there? I remember you said MEMS was missing!

**Comment by syscl** [comment] 2016-11-17 01:31
You should look the many people have already reported that reboot issue under you GUIDE. Reboot behaves unstable..

About MEM2, see [here] (https://github.com/syscl/M3800/blob/M3800/DSDT/patches/syscl_iGPU_MEM2.txt)

syscl

**Comment by maxexcloo** [comment] 2016-11-17 01:34
Thanks!
Are you talking of the shutdown issue where it will start again? Aside from that I haven't seen much about reboot not working, many people are not patching DSDT themselves I think...

**Comment by x4080** [comment] 2016-11-22 04:41
@syscl and @maxexcloo , using your guides I finally solved my 9350 problems, little bugs exists :

- brightness fn key (syscl did you solve it yet?)
- using dw1820A (I'm using wifi dongle as workaround, so no bluetooth)
- touch pad preferences empty (I'm using syscl trackpad kext and work nicely)

@syscl can we open up issues above?

**Comment by syscl** [comment] 2016-11-22 15:31
@x4080 brightness key have to wait AppleSmartTouchPad to update to fix it, seems the author is on the right way...

You have to replace your Wi-Fi to DW 1707 or DW 1830, there's bug in DW 1820 for OS X to switch on it in XPS 13 SKL. So, simply replace it that's fairly the best solution. (Actually you can try to figure out the binary patch for DW 1820 just like the darkvoid to patch for DW 1560, but I am lack of time)

Touchpad pref will be fixed by the author, don't worry. Everything will be fine.

Note: I have 3 exams this month and next month, so I may very possible update my git slower than before, but since XPS 13 9350 on macOS is almost done, I will finish all the things I want before Christmas! Just be patience!

Have a good day, 
syscl

**Comment by x4080** [comment] 2016-11-23 04:01
@syscl Cool ! 👍 

About replacing the wifi card, I feel sorry that I have to get rid of the built in one which works perfectly in windows, do you know reference to try to patch DW 1820? I will try it

Thanks again man for everything, oh btw, I don't need to use any additional kext to automatically wake up my USB wifi after sleep, and your wake up lid patch is very cool

**Comment by syscl** [comment] 2016-11-23 14:29
@x4080 Which spec you have?

You have to use enable kernel debug mode with debug=0x144(if my memory doesn't get mess) to see what's wrong with the kexts that relate to DW 1820.

syscl

**Comment by x4080** [comment] 2016-11-25 00:11
Mine is i7 6500U, QHD+, the argv debug is going to enable it? Right now (I have dual boot), If I boot from windows then boot to Mac, the wifi is recognized, it even can connected but the problem is after sometime, it will connect reconnect like crazy :)

The bluetooth is the same, if using BCM.. kexts, it will connect if I boot first into windows, so I think it just need driver to activate it and solve the connect reconnect, if wifi is connected, it can browse internet normally, but after couple of secs, it will disconnect very strange

Thanks

**Closed** 2016-12-27 05:06 UTC
